### ISSUE TITLE
Stestr does not work with python-subunit 1.4.3

### ISSUE THREAD

**Issue by danpawlik** [mtreinish/stestr#349] opened 2023-09-18 09:05 UTC
**Issue description**

The tox tool is raising an error when  python-subunit 1.4.3 is installed. Error:
```
stestr: 'run' is not a stestr command. See 'stestr --help'.
Did you mean one of these?
  help
  init
  last
```

Tox definition:

```
[testenv]
basepython = python3
install_command = pip install {opts} {packages}
deps = -r{toxinidir}/test-requirements.txt
commands = stestr run {posargs}
             stestr slowest
```

**Expected behavior and actual behavior**

The stestr is starting unit tests.

**Steps to reproduce the problem**
```
git clone https://opendev.org/zuul/zuul-jobs
tox -e py311
```

**Specifications like the version of the project, operating system, or hardware**

**System information**
 - OS: Fedora 38/Centos 9 Stream / Ubuntu 22.03
 - stestr version (`stestr --version`): 4.0.1
 - Python release (`python --version`):  3.11.5
 - pip packages (`pip freeze`):
```
ansible==2.8.20
appdirs==1.4.4
attrs==23.1.0
autopage==0.5.1
azure-core==1.29.4
azure-storage-blob==12.18.1
bcrypt==4.0.1
beautifulsoup4==4.12.2
boto3==1.28.49
botocore==1.31.49
bs4==0.0.1
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
cliff==4.3.0
cmd2==2.4.3
cryptography==41.0.3
decorator==5.1.1
dogpile.cache==1.2.2
fixtures==4.1.0
future==0.18.3
google-api-core==2.11.1
googleapis-common-protos==1.60.0
google-auth==2.23.0
google-cloud-core==2.3.3
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-resumable-media==2.6.0
ibm-cos-sdk==2.13.2
ibm-cos-sdk-core==2.13.2
ibm-cos-sdk-s3transfer==2.13.2
idna==3.4
importlib-metadata==6.8.0
iso8601==2.0.0
isodate==0.6.1
Jinja2==3.1.2
jmespath==1.0.1
jsonpatch==1.33
jsonpointer==2.4
keystoneauth1==5.3.0
MarkupSafe==2.1.3
netifaces==0.11.0
openstacksdk==1.5.0
os-service-types==1.7.0
paramiko==3.3.1
pbr==5.11.1
prettytable==3.9.0
protobuf==4.24.3
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyNaCl==1.5.0
pyperclip==1.8.2
python-dateutil==2.8.2
python-subunit==1.4.3
PyYAML==6.0.1
requests==2.31.0
requestsexceptions==1.4.0
rsa==4.9
s3transfer==0.6.2
six==1.16.0
soupsieve==2.5
stestr==4.0.1
stevedore==5.1.0
testtools==2.6.0
typing_extensions==4.8.0
urllib3==1.26.16
voluptuous==0.13.1
wcwidth==0.2.6
zipp==3.16.2
```

**Additional information**
Downgrading `python-subunit<=1.4.2` resolve the issue.

```
py311: commands[0]> stestr run
{8} roles.generate-zuul-manifest.library.test_generate_manifest.TestFileList.test_symlinks [0.001987s] ... ok
{8} roles.golangci-lint.library.test_golangci_lint_parse_output.TestGolangciLintParseOutput.test_failed_build [0.002158s] ... ok
(...)
```

**Comment by pshchelo** [comment] 2023-09-18 09:37
duplicate of https://github.com/mtreinish/stestr/issues/347
the PR for the fix is already proposed

**Closed** 2023-09-18 09:44 UTC
Labels: bug
