### ISSUE TITLE
gdbm not found running stestr on Mac OSX

### ISSUE THREAD

**Issue by sheyman** [mtreinish/stestr#32] opened 2017-02-20 21:34 UTC
Error trying to run "stestr list" on Mac OSX. Already ran "brew install gdbm".

 I am getting this error:

(stestr27) ➜  stestr git:(testpath) stestr list
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/stestr27/bin/stestr", line 10, in <module>
    sys.exit(main())
  File "/Users/step6927/Projects/stestr/stestr/cli.py", line 102, in main
    sys.exit(args[0].func(args))
  File "/Users/step6927/Projects/stestr/stestr/commands/list.py", line 55, in run
    cmd = conf.get_run_command(_args, ids, filters)
  File "/Users/step6927/Projects/stestr/stestr/config_file.py", line 85, in get_run_command
    repository = util.get_repo_open(options.repo_type, options.repo_url)
  File "/Users/step6927/Projects/stestr/stestr/repository/util.py", line 37, in get_repo_open
    repo_module = importlib.import_module('stestr.repository.' + repo_type)
  File "/usr/local/opt/pyenv/versions/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/step6927/Projects/stestr/stestr/repository/file.py", line 22, in <module>
    from six.moves import dbm_gnu as dbm
  File "/usr/local/opt/pyenv/versions/2.7.9/envs/stestr27/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/opt/pyenv/versions/2.7.9/envs/stestr27/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/opt/pyenv/versions/2.7.9/envs/stestr27/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named gdbm

**Comment by mtreinish** [comment] 2017-02-20 21:41
So I also confirmed this is not working on windows by default. If there isn't an easy install story here, I think we'll have to search and find a better LCD dbm implementation to default on.

This matrix of choices is getting increasingly complex

**Comment by sheyman** [comment] 2017-02-20 21:51
Moving to python 2.7.13 (or later) resolves this.  As you can see above, the error I encountered was on 2.7.9.

See https://docs.python.org/2/library/gdbm.html

**Comment by sheyman** [comment] 2017-02-21 15:29
take a look at https://github.com/mtreinish/stestr/pull/34 which seems to fix the issue on Mac

**Comment by sheyman** [comment] 2017-02-24 16:36
I think the PR is better now.

**Comment by sheyman** [comment] 2017-02-24 22:21
Looks better to me - how doe it look to you?

**Comment by bclau** [comment] 2017-02-27 11:45
What about anydbm [1]? That should also work on Windows.

[1] https://docs.python.org/2/library/anydbm.html

**Comment by mtreinish** [comment] 2017-02-27 14:46
anydbm was originally used. The issue was that by default anydbm was using dbhash which was removed in python3. This resulted in an error if you went from python2 -> python3 in a single file repository. That's why I switched to gdbm because I assumed (incorrectly) that it would be available everywhere.

**Comment by mtreinish** [comment] 2017-03-07 22:42
This is closed now that https://github.com/mtreinish/stestr/commit/952d0d2dc8f2dab876caaa26494e536ed0cedc85 merged

**Closed by mtreinish** 2017-03-07 22:42 UTC
