### ISSUE TITLE
stestr run testname --subunit always return 0 exist status if tests fails

### ISSUE THREAD

**Issue by chkumar246** [mtreinish/stestr#210] opened 2018-12-27 07:10 UTC
### Issue description
stestr is the backend of the tempest run. when invoking tempest run -r <test regex> --subunit and the test_regex fails but the exit status is always returning 0. In tempest run, we donot use --until-failure flag in tempest run cli. 

I am seeing similar issue filed [https://github.com/mtreinish/stestr/issues/68] but it was with --subunit --until-failure, when both flag used together. It is coming with the latest master code when only --subunit flag is used.

#### Expected behavior and actual behavior
stestr run --subunit should return 0 if tests passes and 1 if tests fails.

#### Steps to reproduce the problem

I am adding some tetsts in pull request to reproduce the issue: https://github.com/mtreinish/stestr/pull/209

The related issue is seen when we merged this review https://review.openstack.org/621584
and then we reverted it back https://review.openstack.org/625070

#### Specifications like the version of the project, operating system, or hardware
It is coming with master itself.

**Comment by chkumar246** [comment] 2018-12-27 07:16
Here is the tests failure which reproduces the issue: https://travis-ci.org/mtreinish/stestr/jobs/472563057#L1606

**Comment by mtreinish** [comment] 2019-01-03 03:56
Take a look at the commit message in the fix for issue #68 in PR https://github.com/mtreinish/stestr/pull/69 this is expected behavior. The idea is that we don't want subunit output to fail early since the idea is that there is processing that will handle the output to do the right thing. The non-zero exit code is in the subunit stream already. This is actually how the run command (and load by extension since that's what handles the output for run) works, it uses the subunit stream and relies on the output filter/processing to generate the exit code. I thought this was documented behavior, but it looks like it's only in the stestr manual for the last command instead of for last, load, and run.

**Comment by chkumar246** [comment] 2019-01-04 14:50
Thanks @mtreinish I will update the tempest documentation. Is it feasible to add support for `stestr last --subunit` in tempest as `tempest last --subunit` so that once the tempest run finishes and user can generate subunit in v2 format from the last run. It would be very useful for openstack CI where we run tempest once.
What do you say?

**Comment by mtreinish** [comment] 2019-01-04 15:33
I'm not sure I understand what that buys tempest since it would be a straight pass through to stestr (without any changes), but you can easily add a cli command to tempest using the `stestr.commands.last_command` function. That doesn't really effect stestr, the api is provided so people can do things like that.

To come back to discussing this issue, to close this issue I'm thinking we should just update the stestr manual to more clearly document this edge case. Any other thoughts before I push a patch doing that?

**Comment by chkumar246** [comment] 2019-01-04 15:47
@mtreinish I think we can close this issue. For tempest side, I will add the support for `tempest last --subunit`.

**Closed** 2019-02-28 01:03 UTC
