### ISSUE TITLE
Using --serial and --blacklist-file together does not work

### ISSUE THREAD

**Issue by smatzek** [mtreinish/stestr#103] opened 2017-09-27 11:47 UTC
Using --serial and --blacklist-file parameters together does not work in that the blacklist file is never used.

I believe this is due to the following check in test_processor [1] where it will only list IDs for concurrency == 1 if you pass a filter or a worker path.  I think this should be expanded to check for white list, black list, and black_regex.

In particular this broke the OpenStack Trove gate when ostestr was changed to use stestr.  OpenStack Trove needs to pass --serial and --blacklist-file together to serialize the tests and blacklist some tests for py3.x for one component that hasn't been upgraded to Python 3 support yet.

The workaround for the issue is to pass a regex like '.*' as a test filter.

[1] https://github.com/mtreinish/stestr/blob/master/stestr/test_processor.py#L132

**Comment by mtreinish** [comment] 2017-09-27 19:13
Yep, this is definitely a bug and the line you identified seems to be the cause. It doesn't recognize that it should do the initial discovery there for any of the selection logic mechanisms besides the standard regex. That would get trigger for other cases because of concurrency != 0. I'll push up a fix in a bit

**Comment by mtreinish** [comment] 2017-10-03 22:35
#105 has landed so this should be fixed now.

**Closed by mtreinish** 2017-10-03 22:35 UTC
Labels: bug
